// app/head.tsx
export default function Head() {
    return (
      <>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Assistant:wght@200;400;600;800&display=swap"
          rel="stylesheet"
        />
      </>
    )
  }